Wendy branch 1
JacobHarland/ITSC-3155-Team-6-Final pull request #51
Opened 2022-04-28 00:49 UTC by wDushanin

Implemented Update and Delete Posts

2022-04-28 04:18 UTC, EthanPintoA requested changes

2022-04-28 04:18 UTC, EthanPintoA commented on petpals/blueprints/post_blueprint.py
> +        return render_template("forum.html", posts=posts)
Should be a redirect

2022-04-28 04:18 UTC, EthanPintoA commented on petpals/blueprints/post_blueprint.py
> +@router.route('/posts/delete/<int:post_id>')
Shouldn't have `/posts`

2022-04-28 04:18 UTC, EthanPintoA commented on petpals/blueprints/post_blueprint.py
> +			return render_template("forum.html", posts=posts)
Should be a redirect

2022-04-28 04:18 UTC, EthanPintoA commented on petpals/blueprints/post_blueprint.py
> +			return render_template("posts.html", posts=posts)
`posts.html` does not exit. Should be a redirect to post.html with a post_id of `post_id`

2022-04-28 04:18 UTC, EthanPintoA commented on petpals/blueprints/post_blueprint.py
> +		return render_template("forum.html", posts=posts)
Should be a redirect

2022-05-06 00:31 UTC, wDushanin commented
@EthanPintoA All requested changes have been committed.

2022-05-06 14:09 UTC, EthanPintoA commented
Moved to #74

2022-05-06 14:09 UTC, closed without merging